### ISSUE TITLE
Dear author

### ISSUE THREAD

**Issue by LeoVict** [aseuteurideu/STEAL#2]
Hello, I used your parameter test and did not get the effect proposed in the paper. Is it because the code has not been updated

**Comment by aseuteurideu** [comment]
Hmm, it should be the paper's version. Could you give more detail? What is the command you are running? And what is you pytorch version?

**Comment by LeoVict** [comment]
I just downloaded the trained parameters and ran the "evaluate" code. ped2 AUC is just 86.2%

**Comment by aseuteurideu** [comment]
Hmmm weird.. Just now I tested on other system. Fresh with new git clone, downloaded the dataset and weight from link in the README. And still got 94.4% AUC. What is your pytorch system? I once saw other repo has problem with AUC number because of the pytorch version.
