### ISSUE TITLE
Dear author

### ISSUE THREAD

**Issue by DaheeHan333** [aseuteurideu/STEAL#3]
Hi, this is Dahee Han.
Thanks for your paper and code.

I'm writing to ask you about arguments in train.py.
In your code, there are args.pseudo_anomaly_jump_inpainting at 42 and 54 lines.
Does it mean args.pseudo_anomaly_jump?

It would be very helpful if you check and answer it.

**Comment by aseuteurideu** [comment]
Hi, thank you for letting me know the problem.
I fixed the problem. You can pull the change.
