### ISSUE TITLE
Dear author

### ISSUE THREAD

**Issue by DaheeHan333** [aseuteurideu/STEAL#4]
Hello, I'm training and testing on this.
I would like to know why the last 16 frames are excluded on training.

Thanks.

**Comment by aseuteurideu** [comment]
Is it? I don't remember it being like that. May be bug that I don't recognize, so thank you for notifying. I'll check later. Anyway, I think it will not affect the performance much.

**Comment by DaheeHan333** [comment]
I was watching at 71 lines at model/utils.py. 
Maybe I misunderstand what it is meaning. 
It would be very helpful if you check it. 

Thanks!

**Comment by aseuteurideu** [comment]
Ah I see.. My schedule is kinda tight now so can't check directly. But may be line 86 at model/utils.py can explain. After taking the first index, the last 16 will be included.

**Comment by DaheeHan333** [comment]
I finally understood. 
I appreciate it.

**Comment by aseuteurideu** [comment]
Alright! If there is no problem, I'll close this issue
