### ISSUE TITLE
About the parameter P

### ISSUE THREAD

**Issue by wangrui12345678** [aseuteurideu/STEAL#5]
hello,i have a quenstion:in paper,the p is 0.01,but in readme,p is 0.2,which one is true?moreover,i used 0.2 to train the code,Using my own training parameters and weights,the AUC of STEAL NET is 93.80%,why?

**Comment by aseuteurideu** [comment]
I am sorry for the confusion. The paper is the correct one. p=0.01.

**Comment by Forchapeatl** [comment]
@aseuteurideu  and @wangrui12345678  please help me . I keep getting index out of range on google colab.

![image](https://user-images.githubusercontent.com/24577149/179630688-1dd64212-ab9a-4596-99fb-f1e575fbd1ff.png)
